fitness_management_system/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    path('',
         RedirectView.as_view(
             pattern_name='about_urlpattern',
             permanent=False
         )),
    path('login/',
         LoginView.as_view(template_name='workoutinfo/login.html'),
         name='login_urlpattern'
         ),
    path('logout/',
         LogoutView.as_view(),
         name='logout_urlpattern'
         ),
    path('about/',
         TemplateView.as_view(
            template_name='workoutinfo/about.html'),
            name='about_urlpattern'
         ),

    path('admin/', admin.site.urls),
    path('', include('workoutinfo.urls'))
]

workoutinfo/urls.py
from django.urls import path
from workoutinfo.views import (
    MemberList,
    TrainerList,
    WorkoutPlanList,
    WorkoutList,
    NutritionPlanList,
    MembershipList,
    PaymentList,
    MemberDetail,
    TrainerDetail,
    NutritionPlanDetail,
    WorkoutPlanDetail,
    WorkoutDetail,
    MembershipDetail,
    PaymentDetail,
    MemberCreate,
    TrainerCreate,
    WorkoutPlanCreate,
    WorkoutCreate,
    NutritionPlanCreate,
    MembershipCreate,
    PaymentCreate,
    MemberUpdate,
    TrainerUpdate,
    WorkoutPlanUpdate,
    WorkoutUpdate,
    NutritionPlanUpdate,
    MembershipUpdate,
    PaymentUpdate,
    WorkoutDelete,
    NutritionPlanDelete,
    PaymentDelete,
    MemberDelete,
    TrainerDelete,
    WorkoutPlanDelete,
    MembershipDelete,
)


urlpatterns = [
    path('member/',
         MemberList.as_view(),
         name='workoutinfo_member_list_urlpattern'),

    path('member/<int:pk>/',
         MemberDetail.as_view(),
         name='workoutinfo_member_detail_urlpattern'),

    path('member/create/',
         MemberCreate.as_view(),
         name='workoutinfo_member_create_urlpattern'),

    path('member/<int:pk>/update/',
         MemberUpdate.as_view(),
         name='workoutinfo_member_update_urlpattern'),

    path('member/<int:pk>/delete/',
         MemberDelete.as_view(),
         name='workoutinfo_member_delete_urlpattern'),

    path('trainer/',
         TrainerList.as_view(),
         name='workoutinfo_trainer_list_urlpattern'),

    path('trainer/<int:pk>/',
         TrainerDetail.as_view(),
         name='workoutinfo_trainer_detail_urlpattern'),

    path('trainer/create/',
         TrainerCreate.as_view(),
         name='workoutinfo_trainer_create_urlpattern'),

    path('trainer/<int:pk>/update/',
         TrainerUpdate.as_view(),
         name='workoutinfo_trainer_update_urlpattern'),

    path('trainer/<int:pk>/delete/',
         TrainerDelete.as_view(),
         name='workoutinfo_trainer_delete_urlpattern'),

    path('workoutplan/',
         WorkoutPlanList.as_view(),
         name='workoutinfo_workoutplan_list_urlpattern'),

    path('workoutplan/<int:pk>/',
         WorkoutPlanDetail.as_view(),
         name='workoutinfo_workoutplan_detail_urlpattern'),

    path('workoutplan/create/',
         WorkoutPlanCreate.as_view(),
         name='workoutinfo_workoutplan_create_urlpattern'),

    path('workoutplan/<int:pk>/update/',
         WorkoutPlanUpdate.as_view(),
         name='workoutinfo_workoutplan_update_urlpattern'),

    path('workoutplan/<int:pk>/delete/',
         WorkoutPlanDelete.as_view(),
         name='workoutinfo_workoutplan_delete_urlpattern'),

    path('workout/',
         WorkoutList.as_view(),
         name='workoutinfo_workout_list_urlpattern'),

    path('workout/<int:pk>/',
         WorkoutDetail.as_view(),
         name='workoutinfo_workout_detail_urlpattern'),

    path('workout/create/',
         WorkoutCreate.as_view(),
         name='workoutinfo_workout_create_urlpattern'),

    path('workout/<int:pk>/update/',
         WorkoutUpdate.as_view(),
         name='workoutinfo_workout_update_urlpattern'),

    path('workout/<int:pk>/delete/',
         WorkoutDelete.as_view(),
         name='workoutinfo_workout_delete_urlpattern'),

    path('nutritionplan/',
         NutritionPlanList.as_view(),
         name='workoutinfo_nutritionplan_list_urlpattern'),

    path('nutritionplan/<int:pk>/',
         NutritionPlanDetail.as_view(),
         name='workoutinfo_nutritionplan_detail_urlpattern'),

    path('nutritionplan/create/',
         NutritionPlanCreate.as_view(),
         name='workoutinfo_nutritionplan_create_urlpattern'),

    path('nutritionplan/<int:pk>/update/',
         NutritionPlanUpdate.as_view(),
         name='workoutinfo_nutritionplan_update_urlpattern'),

    path('nutritionplan/<int:pk>/delete/',
         NutritionPlanDelete.as_view(),
         name='workoutinfo_nutritionplan_delete_urlpattern'),

    path('membership/',
         MembershipList.as_view(),
         name='workoutinfo_membership_list_urlpattern'),

    path('membership/<int:pk>/',
         MembershipDetail.as_view(),
         name='workoutinfo_membership_detail_urlpattern'),

    path('membership/create/',
         MembershipCreate.as_view(),
         name='workoutinfo_membership_create_urlpattern'),

    path('membership/<int:pk>/update/',
         MembershipUpdate.as_view(),
         name='workoutinfo_membership_update_urlpattern'),

    path('membership/<int:pk>/delete/',
         MembershipDelete.as_view(),
         name='workoutinfo_membership_delete_urlpattern'),

    path('payment/',
         PaymentList.as_view(),
         name='workoutinfo_payment_list_urlpattern'),

    path('payment/<int:pk>/',
         PaymentDetail.as_view(),
         name='workoutinfo_payment_detail_urlpattern'),

    path('payment/create/',
         PaymentCreate.as_view(),
         name='workoutinfo_payment_create_urlpattern'),

    path('payment/<int:pk>/update/',
         PaymentUpdate.as_view(),
         name='workoutinfo_payment_update_urlpattern'),

    path('payment/<int:pk>/delete/',
         PaymentDelete.as_view(),
         name='workoutinfo_payment_delete_urlpattern'),
]

workoutinfo/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.db.models import UniqueConstraint
from django.urls import reverse


# Create your models here.
class Member(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    OTHER = 'O'

    GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHER, 'Other'),
    ]
    member_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    disambiguator = models.CharField(max_length=45, blank=True, default='')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone_number = models.CharField(
        max_length=15,
        validators=[RegexValidator(
            r'^\+?\d{9,15}$',
            'Enter a valid phone number.'
        )]
    )

    def __str__(self):
        if self.disambiguator == '':
            return '%s, %s' % (self.last_name, self.first_name)
        else:
            result = '%s, %s (%s)' % (self.last_name, self.first_name, self.disambiguator)
        return result

    def get_absolute_url(self):
        return reverse('workoutinfo_member_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('workoutinfo_member_update_urlpattern',
                        kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('workoutinfo_member_delete_urlpattern',
                        kwargs={'pk': self.pk})

    class Meta:
        ordering = ['last_name', 'first_name', 'disambiguator']
        constraints = [
            models.UniqueConstraint(fields=['last_name', 'first_name', 'phone_number'], name='unique_member')
        ]


class Trainer(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    member_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    disambiguator = models.CharField(max_length=45, blank=True, default='')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone_number = models.CharField(
        max_length=15,
        validators=[RegexValidator(
            r'^\+?\d{9,15}$',
            'Enter a valid phone number.'
        )]
    )

    def __str__(self):
        if self.disambiguator == '':
            return '%s, %s' % (self.last_name, self.first_name)
        else:
            result = '%s, %s (%s)' % (self.last_name, self.first_name, self.disambiguator)
        return result

    def get_absolute_url(self):
        return reverse('workoutinfo_trainer_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('workoutinfo_trainer_update_urlpattern',
                        kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('workoutinfo_trainer_delete_urlpattern',
                        kwargs={'pk': self.pk})

    class Meta:
        ordering = ['last_name', 'first_name', 'disambiguator']
        constraints = [
            UniqueConstraint(fields=['last_name', 'first_name', 'phone_number'], name='unique_trainer')
        ]


class WorkoutPlan(models.Model):
    workout_plan_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    member = models.ForeignKey(Member, related_name='workoutplans', on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.member} - {self.name}"

    def get_absolute_url(self):
        return reverse('workoutinfo_workoutplan_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('workoutinfo_workoutplan_update_urlpattern',
                        kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('workoutinfo_workoutplan_delete_urlpattern',
                        kwargs={'pk': self.pk})

    class Meta:
        ordering = ['member', 'name']
        constraints = [
            UniqueConstraint(fields=['name', 'member'], name='unique_workoutplan')
        ]


class Workout(models.Model):
    workout_id = models.AutoField(primary_key=True)
    date = models.DateField()
    name = models.CharField(max_length=255)
    description = models.TextField()
    duration = models.IntegerField(help_text='Enter duration in minutes')
    workout_plan = models.ForeignKey(WorkoutPlan, related_name='workouts', on_delete=models.PROTECT)
    member = models.ForeignKey(Member, related_name='workouts', on_delete=models.PROTECT)
    trainer = models.ForeignKey(Trainer, related_name='workouts', on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.member} - {self.name} / {self.date} / {self.trainer}"

    def get_absolute_url(self):
        return reverse('workoutinfo_workout_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('workoutinfo_workout_update_urlpattern',
                        kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('workoutinfo_workout_delete_urlpattern',
                        kwargs={'pk': self.pk})

    class Meta:
        ordering = ['member', 'name', 'date']
        constraints = [
            UniqueConstraint(fields=['member', 'name'], name='unique_workout')
        ]


class NutritionPlan(models.Model):
    TIME_CHOICES = [
        ('breakfast', 'BREAKFAST'),
        ('lunch', 'LUNCH'),
        ('dinner', 'DINNER'),
    ]
    nutrition_plan_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    member = models.ForeignKey(Member, related_name='nutritionplans', on_delete=models.PROTECT)
    trainer = models.ForeignKey(Trainer, related_name='nutritionplans', on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.member} - {self.name} / {self.trainer}"

    def get_absolute_url(self):
        return reverse('workoutinfo_nutritionplan_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('workoutinfo_nutritionplan_update_urlpattern',
                        kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('workoutinfo_nutritionplan_delete_urlpattern',
                        kwargs={'pk': self.pk})

    class Meta:
        ordering = ['member', 'name', 'trainer']
        constraints = [
            UniqueConstraint(fields=['member', 'name'], name='unique_nutritionplan')
        ]


class Membership(models.Model):
    membership_id = models.AutoField(primary_key=True)
    start_date = models.DateField()
    end_date = models.DateField()
    member = models.ForeignKey(Member, related_name='memberships', on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.member} ({self.start_date} ~ {self.end_date})"

    def get_absolute_url(self):
        return reverse('workoutinfo_membership_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('workoutinfo_membership_update_urlpattern',
                        kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('workoutinfo_membership_delete_urlpattern',
                        kwargs={'pk': self.pk})

    class Meta:
        ordering = ['member', 'start_date', 'end_date']
        constraints = [
            UniqueConstraint(fields=['member', 'start_date', 'end_date'], name='unique_membership')
        ]


class Payment(models.Model):
    PAYMENT_METHOD_CHOICES = (
        ('credit_card', 'Credit Card'),
        ('debit_card', 'Debit Card'),
        ('paypal', 'PayPal'),
        ('google_pay', 'Google Pay'),
        ('apple_pay', 'Apple Pay'),
        ('other', 'Other'),
    )
    payment_id = models.AutoField(primary_key=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, help_text='Enter the amount in USD')
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES)
    payment_date = models.DateField(auto_now_add=True)
    membership = models.ForeignKey(Membership, related_name='payments', on_delete=models.PROTECT)
    member = models.ForeignKey(Member, related_name='payments', on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.member} / {self.membership.start_date} ~ {self.membership.end_date}"
    
    def get_absolute_url(self):
        return reverse('workoutinfo_payment_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('workoutinfo_payment_update_urlpattern',
                        kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('workoutinfo_payment_delete_urlpattern',
                        kwargs={'pk': self.pk})

    class Meta:
        ordering = ['member', 'payment_date']

workoutinfo/templates/workoutinfo/member_detail.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Member - {{ member }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ member }}</h2>
                <ul class="inline">
                    {% if perms.workoutinfo.change_member %}
                        <li>
                            <a href="{{ member.get_update_url }}"
                             class="button button-primary">
                            Edit Member</a></li>
                    {% endif %}
                    {% if perms.workoutinfo.delete_member %}
                        <li>
                            <a href="{{ member.get_delete_url }}"
                             class="button button-primary">
                            Delete Member</a></li>
                    {% endif %}
                 </ul>

                <section>
                    <table>
                        <tr>
                            <th>First Name:</th>
                            <td>{{ member.first_name }}</td>
                        </tr>
                        <tr>
                            <th>Last Name:</th>
                            <td>{{ member.last_name }}</td>
                        </tr>
                        {% if member.disambiguator %}
                            <tr>
                                <th>Disambiguator:</th>
                                <td>{{ member.disambiguator }}</td>
                            </tr>
                        {% endif %}
                        <tr>
                            <th>Gender:</th>
                            <td>{{ member.gender }}</td>
                        </tr>
                        <tr>
                            <th>Phone Number:</th>
                            <td>{{ member.phone_number }}</td>
                        </tr>
                    </table>
                </section>

                <section>
                    <h3>Membership</h3>
                    <ul>
                        {% for membership in membership_list %}
                            <li>
                                <a href="{{ membership.get_absolute_url }}">{{ membership }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no memberships for this member.</em></li>
                        {% endfor %}
                    </ul>
                </section>

                <section>
                    <h3>Workout Plan</h3>
                    <ul>
                        {% for workoutplan in workoutplan_list %}
                            <li>
                                <a href="{{ workoutplan.get_absolute_url }}">{{ workoutplan }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no workoutplans for this member.</em></li>
                        {% endfor %}
                    </ul>
                </section>

                <section>
                    <h3>Workout</h3>
                    <ul>
                        {% for workout in workout_list %}
                            <li>
                                <a href="{{ workout.get_absolute_url }}">{{ workout }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no workouts for this member.</em></li>
                        {% endfor %}
                    </ul>
                </section>

                <section>
                    <h3>Nutrition Plan</h3>
                    <ul>
                        {% for nutritionplan in nutritionplan_list %}
                            <li>
                                <a href="{{ nutritionplan.get_absolute_url }}">{{ nutritionplan }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no nutritionplans for this member.</em></li>
                        {% endfor %}
                    </ul>
                </section>
            </div>
        </div> <!-- row -->
    </article>

{% endblock %}

workoutinfo/templates/workoutinfo/member_form.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Create Member
{% endblock %}

{% block content %}
    <form
        action="{% url 'workoutinfo_member_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">
        Create Member</button>
    </form>
{% endblock %}

workoutinfo/templates/workoutinfo/member_form_update.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Update Member
{% endblock %}

{% block content %}
    <form
        action="{{ member.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">Update Member</button>
    </form>
{% endblock %}

workoutinfo/templates/workoutinfo/membership_confirm_delete.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Delete Membership
{% endblock %}

{% block content %}
    <form
        action="{{ membership.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            membership {{ membership }}?
        </p>
        <a href="{{ membership.get_absolute_url }}"
            class="button button-primary">
            Cancel</a>
        <button type="submit" class="button button-primary">Delete Membership</button>
    </form>
{% endblock %}

workoutinfo/templates/workoutinfo/membership_form_update.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Update Membership
{% endblock %}

{% block content %}
    <form
        action="{{ membership.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">Update Membership</button>
    </form>
{% endblock %}

workoutinfo/templates/workoutinfo/membership_refuse_delete.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Error Deleting Membership
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Membership</h2>
        <p>
            You may not delete membership {{ membership }}.  This
            membership is currently associated with below payment:
        </p>

        <ul>
            {% for payment in payment %}
            <li><a href="{{ payment.get_absolute_url }}">{{ payment }}</a></li>
            {%  endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'workoutinfo_member_list_urlpattern' %}">Member List</a>.
        </p>
    </div>
{% endblock %}

workoutinfo/templates/workoutinfo/nutritionplan_detail.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Nutrition Plan - {{ nutritionplan }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ nutritionplan }}</h2>
                <ul class="inline">
                    {% if perms.workoutinfo.change_nutritionplan %}
                        <li>
                          <a href="{{ nutritionplan.get_update_url }}"
                             class="button button-primary">
                            Edit Nutrition Plan</a></li>
                    {% endif %}
                    {% if perms.workoutinfo.delete_nutritionplan %}
                        <li>
                          <a href="{{ nutritionplan.get_delete_url }}"
                             class="button button-primary">
                            Delete Nutrition Plan</a></li>
                    {% endif %}
                </ul>
                <section>
                    <table>
                        <tr>
                            <th>Member:</th>
                                <td><a href="{{ member.get_absolute_url }}">{{ member }}</a></td>
                        </tr>
                        <tr>
                            <th>Trainer:</th>
                            <td><a href="{{ trainer.get_absolute_url }}">{{ trainer }}</a></td>
                        </tr>
                    </table>
                </section>

                <section>
                    <table>
                        <tr>
                            <th>Nutrition Name:</th>
                            <td>{{ nutritionplan.name }}</td>
                        </tr>
                        <tr>
                            <th>Description:</th>
                            <td>{{ nutritionplan.description }}</td>
                        </tr>
                    </table>
                </section>
            </div>
        </div> <!-- row -->
    </article>
{% endblock %}

workoutinfo/templates/workoutinfo/nutritionplan_form.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Create Nutrition Plan
{% endblock %}

{% block content %}
    <form
        action="{% url 'workoutinfo_nutritionplan_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">
        Create Nutrition Plan</button>
    </form>
{% endblock %}

workoutinfo/templates/workoutinfo/payment_detail.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Payment - {{ payment }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ payment }}</h2>
                <ul class="inline">
                    {% if perms.workoutinfo.change_payment %}
                        <li>
                          <a href="{{ payment.get_update_url }}"
                             class="button button-primary">
                            Edit Payment</a></li>
                    {% endif %}

                    {% if perms.workoutinfo.delete_payment %}
                        <li>
                          <a href="{{ payment.get_delete_url }}"
                             class="button button-primary">
                            Delete Payment</a></li>
                    {% endif %}
                </ul>
                <section>
                    <table>
                        <tr>
                            <th>Membership:</th>
                            <td><a href="{{ membership.get_absolute_url }}">{{ membership }}</a></td>
                        </tr>
                    </table>
                </section>

                <section>
                    <table>
                        <tr>
                            <th>Amount:</th>
                            <td>{{ payment.amount }}</td>
                        </tr>
                        <tr>
                            <th>Payment Method:</th>
                            <td>{{ payment.payment_method }}</td>
                        </tr>
                        <tr>
                            <th>Payment Date:</th>
                            <td>{{ payment.payment_date }}</td>
                        </tr>
                    </table>
                </section>
            </div>
        </div> <!-- row -->
    </article>
{% endblock %}

workoutinfo/templates/workoutinfo/trainer_confirm_delete.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Delete Trainer
{% endblock %}

{% block content %}
    <form
        action="{{ trainer.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            trainer {{ trainer }}?
        </p>
        <a href="{{ trainer.get_absolute_url }}"
            class="button button-primary">
            Cancel</a>
        <button type="submit" class="button button-primary">Delete Trainer</button>
    </form>
{% endblock %}

workoutinfo/templates/workoutinfo/trainer_form.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Create Trainer
{% endblock %}

{% block content %}
    <form
        action="{% url 'workoutinfo_trainer_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">
        Create Trainer</button>
    </form>
{% endblock %}

workoutinfo/templates/workoutinfo/workout_form.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Create Workout
{% endblock %}

{% block content %}
    <form
        action="{% url 'workoutinfo_workout_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">
        Create Workout</button>
    </form>
{% endblock %}

workoutinfo/templates/workoutinfo/workout_form_update.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Update Workout
{% endblock %}

{% block content %}
    <form
        action="{{ workout.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">Update Workout</button>
    </form>
{% endblock %}

workoutinfo/templates/workoutinfo/workoutplan_form.html
{% extends 'workoutinfo/base.html' %}

{% block title %}
    Create Trainer
{% endblock %}

{% block content %}
    <form
        action="{% url 'workoutinfo_trainer_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">
        Create Trainer</button>
    </form>
{% endblock %}